### PR TITLE
Translation Updates

### PR DESCRIPTION
**Pull request by ININ-TransifexAutomation**
Translation Process Automation generated string (DO NOT EDIT): [app/translations/webrtc-troubleshoot/zh-tw.json]

### CODE REVIEW

**Comment by kiyoshiiwase** [comment]
It looks good to me (except extra indentation Transifex has added). Please merge if it is okay with you.

**Comment by xdumaine** [comment]
I can add an ignore rule to the translation directory for styles.

**Comment by xdumaine** [comment]
@jbelmont could you help with that, please?

**Comment by xdumaine** [comment]
@jbelmont Thanks for merging this! Could you please publish a patch version?

**Pull request merged**
